### ISSUE TITLE
bug: 时不时autosub会out of range, 需要检查逻辑

### ISSUE THREAD

**Issue by March-mitsuki** [March-mitsuki/vvvorld#4]
`goroutine 163 [running]:
github.com/March-mitsuki/satla-backend/controllers.makeAutoPreview(_, _)
        /home/mitsuki/repos/github/satla/satla-backend/controllers/ws_handler_auto.go:344 +0x615
github.com/March-mitsuki/satla-backend/controllers.setAutoStatToRedis({0xc0002dedf0?, 0xc0002dee00?}, 0xc000364300, 0xc0000c9308, 0x0)
        /home/mitsuki/repos/github/satla/satla-backend/controllers/ws_handler_auto.go:904 +0x105
github.com/March-mitsuki/satla-backend/controllers.broadcastCommonStopPlay({0xc0002dedf0?, 0xc0002dee00?}, 0xc000364300, 0x1?)
        /home/mitsuki/repos/github/satla/satla-backend/controllers/ws_handler_auto.go:532 +0x12d
github.com/March-mitsuki/satla-backend/controllers.manualAutoSend({0xcf8418, 0xc00032c240}, {0xc0002dedf0?, 0xc0002dee00?}, 0xc000364300, 0xc0000c9308, 0xc000364300?, 0xc0004ce000?)
        /home/mitsuki/repos/github/satla/satla-backend/controllers/ws_handler_auto.go:276 +0x253
created by github.com/March-mitsuki/satla-backend/controllers.cancelableSleep
        /home/mitsuki/repos/github/satla/satla-backend/controllers/ws_handler_auto.go:500 +0x1885`

**Comment by March-mitsuki** [comment]
可能是点击下一句过快的导致的，需要检查函数互相之间异步调用时的的顺序
